### ISSUE TITLE
cannot download the dataset

### ISSUE THREAD

**Issue by ysunbp** [qingping95/DECO-F#1]
Hi! I have tried to clone your project using Github Desktop. However, it suggests that the dataset enclosed does not exist on the server. Could you please give me some suggestions? Thanks!

![image](https://user-images.githubusercontent.com/41725714/147896053-e64172c7-4706-443b-9ffc-a3c81364cdb4.png)

**Comment by qingping95** [comment]
@ysunbp please try again.

**Comment by ysunbp** [comment]
Thanks! The issue is resolved.
